### ISSUE TITLE
 Show count of errors on the Filter pop-up

### ISSUE THREAD

**Issue by SLornieCYC** [data-to-insight/cin-validator-fe#154]
I've always found this feature very helpful on the 903 tool so would be good to have on the CIN FE too! (Especially as the plan seems to be to retire the original 903 FE and combine it with this one).  

Current CIN FE | Current 903 FE
--- | ---
![image](https://github.com/data-to-insight/cin-validator-fe/assets/89449804/199d94c6-df1c-4f2f-aa8c-ec00a39b9ad0) | ![image](https://github.com/data-to-insight/cin-validator-fe/assets/89449804/34df6e9f-6d7f-4776-92db-b0f4eb63c464)

Note that the filter on the 903 FE also lists the error codes in descending order by count of ocurrences (vs alphabetically by code on CIN FE).  I wonder if it would be possible to re-sort the list of error codes table by clicking on the table headings?

**Comment by tab1tha** [comment]
This is a good suggestion @SLornieCYC , Thank you !
We'll look into it.

**Comment by dotloadmovie** [comment]
OK, picking this up

**Comment by dotloadmovie** [comment]
Will need:
- tracking error count in the ReportReducer when we parse out the response and assign errors to childIDs
- Sortable solumn headers on @sf-mui-components/Table
