### ISSUE TITLE
FE should state rule engine version 

### ISSUE THREAD

**Issue by SLornieCYC** [data-to-insight/cin-validator-fe#160]
At the moment the FE gives details of it's own version, but there is nothing that tells the user which version of the **python rules** are being executed (e.g. so they could then check the github for the rule coding if they notice an issue, or to see if something has already been reported/fixed but just not deployed to live yet).  

Obviously this applies equally to https://github.com/data-to-insight/CIN-validator and https://github.com/data-to-insight/quality-lac-data-beta-validator (once that is re-deployed using the new shared FE - EDIT should this one be renamed from quality-lac-data-beta now?).  Not sure about the practicalities here e.g. whether it could be done via the releases versioning on github or would need a manually recorded version/datestamp somewhere in both products.

![image](https://github.com/data-to-insight/cin-validator-fe/assets/89449804/3c1bac29-4f57-4509-942f-81cf2e64afa1)

**Comment by tab1tha** [comment]
This is a good suggestion, @SLornieCYC 
I can see how useful that'll be.
